// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZcY8SAlCGGyzRjjsC_rF5Tqe66KtzxNw',
    appId: '1:121786814029:web:71f4a8ed33a432a100d604',
    messagingSenderId: '121786814029',
    projectId: 'clothes-440f9',
    authDomain: 'clothes-440f9.firebaseapp.com',
    databaseURL: 'https://clothes-440f9-default-rtdb.firebaseio.com',
    storageBucket: 'clothes-440f9.appspot.com',
    measurementId: 'G-479VSE3662',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2zDis7oRZMKpma_3wQNtRFN_RipN3hY',
    appId: '1:121786814029:android:f2ba5c532587fe9000d604',
    messagingSenderId: '121786814029',
    projectId: 'clothes-440f9',
    databaseURL: 'https://clothes-440f9-default-rtdb.firebaseio.com',
    storageBucket: 'clothes-440f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8PN263gn4M8DcuuXD6HBANOgeL0BurMg',
    appId: '1:121786814029:ios:6e797191cae5b10900d604',
    messagingSenderId: '121786814029',
    projectId: 'clothes-440f9',
    databaseURL: 'https://clothes-440f9-default-rtdb.firebaseio.com',
    storageBucket: 'clothes-440f9.appspot.com',
    androidClientId: '121786814029-45fbrpr5ofug1ps8d3sm2o50an816m93.apps.googleusercontent.com',
    iosClientId: '121786814029-jekcadbvqc69t6515osedeujnfbsl4l4.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothesShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8PN263gn4M8DcuuXD6HBANOgeL0BurMg',
    appId: '1:121786814029:ios:6e797191cae5b10900d604',
    messagingSenderId: '121786814029',
    projectId: 'clothes-440f9',
    databaseURL: 'https://clothes-440f9-default-rtdb.firebaseio.com',
    storageBucket: 'clothes-440f9.appspot.com',
    androidClientId: '121786814029-45fbrpr5ofug1ps8d3sm2o50an816m93.apps.googleusercontent.com',
    iosClientId: '121786814029-jekcadbvqc69t6515osedeujnfbsl4l4.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothesShop',
  );
}
